[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.generate]
dependencies = ["build"]
script = '''
    mkdir -p build/rust
    for f in test/files/valid/*; do
        if [[ -f $f ]]; then
            echo "Generating $f"
            target/debug/codegen $f -o build/rust/$(basename -s .fbs $f).rs \
                || echo "Failed to generate $(basename $f)"
        fi
    done

    for f in test/files/invalid/*; do
        if [[ -f $f ]]; then
            echo -n "Testing $f: "
            target/debug/codegen $f -o build/rust/$(basename -s .fbs $f).rs 2>/dev/null && true
            res=$?
            if [[ $res -eq 0 ]]; then
                echo -e "\e[0;31mcompiled\e[0m"
            elif [[ $res -eq 101 ]]; then
                echo -e "\e[0;31mpanic\e[0m"
            else
                echo -e "\e[0;32msuccess\e[0m"
            fi
        fi
    done
'''

[tasks.commit-check]
script = '''
cargo fmt --all -- --check
cargo clippy --all-targets -- -D warnings
cargo test
'''