[package]
name = "planus-example"
version = "0.1.0"
edition = "2021"

[dependencies]
planus = { version = "0.1", path = "../../planus" }
serde = { version = "1.0.132", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.73"
